format_version: 5
pipelines:
  diary-docker:
    group: diary
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    environment_variables:
      AWS_ACCESS_KEY_ID: AKIA5G2AKNTSNENMAU6Z
    secure_variables:
      AWS_SECRET_ACCESS_KEY: "AES:g59K4IT1d4/zNeXfMNl1Pg==:dTJgdXqmIkHzL07B5Dq3hN/E5k7m9uPNlRV+jLPLHm1TPLxav9yUre26PBiEF/xo"
    stages:
      - build-base:
          clean_workspace: true
          jobs:
            r:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-r-base"
      - build-dojo:
          clean_workspace: true
          jobs:
            r:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-r-dojo"
            node:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-node-dojo"
            tex:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-tex-dojo"
      - test:
          clean_workspace: true
          jobs:
            node-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-node-dojo"
            r-base:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-r-base"
            r-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-r-dojo"
            tex-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-tex-dojo"
      - save:
          clean_workspace: true
          environment_variables:
            GIT_AUTHOR_NAME: GoCD pipeline
            GIT_AUTHOR_EMAIL: diary@gocd.martinmccaffery.com
            GIT_COMMITTER_NAME: GoCD pipeline
            GIT_COMMITTER_EMAIL: diary@gocd.martinmccaffery.com
          jobs:
            update-diary:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "gocd-dependencies-push-update"

  diary-docker-update:
    group: diary
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        auto_update: false
    environment_variables:
      GIT_AUTHOR_NAME: GoCD pipeline
      GIT_AUTHOR_EMAIL: diary-docker@gocd.martinmccaffery.com
      GIT_COMMITTER_NAME: GoCD pipeline
      GIT_COMMITTER_EMAIL: diary-docker@gocd.martinmccaffery.com
    stages:
      - get-updates:
          clean_workspace: true
          approval: manual
          tasks:
           - exec:
               command: make
               arguments:
                - gocd-dependencies-get-updates
