ARG BASE_IMAGE=ubuntu:22.04
FROM --platform=linux/x86_64 $BASE_IMAGE

# This file installs node.js, and a load of packages, on a base Ubuntu image.

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ENV NODE_VERSION 18.13.0
RUN apt-get update \
	&& apt-get install --no-install-recommends -y \
		ca-certificates \
		curl \
		graphviz \
		less \
		make \
		mysql-client \
		netcat \
		wget \
	&& apt-get clean \
	&& curl -L -o node.tar.gz "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" \
	&& tar -xf node.tar.gz -C /usr/local --strip-components=1 \
	&& rm node.tar.gz \
	&& ln -s /usr/local/bin/node /usr/local/bin/nodejs

# Install yarn
ENV YARN_VERSION 1.22.19
RUN curl -L -o yarn.tar.gz "https://yarnpkg.com/downloads/${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz" && \
	tar -xzf yarn.tar.gz -C /opt/ && \
	rm yarn.tar.gz && \
	ln -s /opt/yarn-v${YARN_VERSION}/bin/yarn /usr/local/bin/yarn && \
	ln -s /opt/yarn-v${YARN_VERSION}/bin/yarnpkg /usr/local/bin/yarnpkg

# Preinstall packages whose binaries need to be accessible from the terminal
RUN yarn global add \
	db-migrate@^0.11.13 \
	db-migrate-mysql@^2.2.0 \
	newman@^5.3.2
