FROM r-base:3.6.2

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN apt-get update &&\
	apt-get install -y --allow-downgrades \
		libcurl4-openssl-dev libxml2-dev \
		libmariadbclient-dev libssl-dev \
		libcairo2-dev \
		ssh-client mysql-client make netcat && \
	apt-get clean

COPY package-*.r /usr/src/
RUN chmod +x /usr/src/package-install.r
RUN cd /usr/src && ./package-install.r

COPY docker-r-dojo/tests/test.r docker-r-dojo/tests/test.r
