FROM --platform=linux/x86_64 ubuntu:noble
ENV DEBIAN_FRONTEND=noninteractive

# Based on https://github.com/blang/latex-docker/blob/master/Dockerfile.ubuntu
RUN apt-get update -q && apt-get install -qy \
    gnuplot \
    git \
    make \
    python3-pygments \
    texlive-full \
    && rm -rf /var/lib/apt/lists/*

ENV TINI_VERSION=v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Install packages and Dojo scripts
ENV DOJO_VERSION=0.13.3
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    make \
    poppler-utils \
    sudo \
  && apt-get clean \
  && sudo deluser ubuntu \
  && git clone --depth 1 -b ${DOJO_VERSION} https://github.com/kudulab/dojo.git /tmp/dojo_git \
  && /tmp/dojo_git/image_scripts/src/install.sh \
  && rm -r /tmp/dojo_git

RUN apt-get update \
  && apt-get install -y inkscape \
  && apt-get clean

COPY docker-tex-dojo/wordcount /usr/bin/

ENV TEXCOUNT_VERSION=3_2_0_41 \
    LC_CTYPE=C \
    LC_ALL=C \
    LANG=C
RUN curl https://app.uio.no/ifi/texcount/download.php?file=texcount_${TEXCOUNT_VERSION}.zip -o texcount.zip \
    && unzip texcount.zip -d texcount \
    && mv texcount/texcount.pl /usr/bin/ \
    && rm -rf texcount/ \
    && chmod +x /usr/bin/wordcount /usr/bin/texcount.pl

WORKDIR /dojo/work

ENTRYPOINT ["/tini", "-g", "--", "/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]
