ARG BASE_IMAGE
FROM --platform=linux/x86_64 $BASE_IMAGE

# Tools found only on the composite, without their own bespoke images

# Terraform repository
RUN (curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -) && \
  apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

ENV AWS_CLI_VERSION=2.17.27
RUN cd /tmp/ \
  && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip" -o "awscliv2.zip" \
  && unzip -q awscliv2.zip \
  && ./aws/install \
  && curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb" \
  && dpkg -i session-manager-plugin.deb \
  && rm -rf ./aws awscliv2.zip session-manager-plugin.deb

# These lines will show what versions of these tools are available.
# RUN apt-cache policy ansible && false
# RUN apt-cache policy terraform && false

# repository packages
ENV TERRAFORM_VERSION=1.9.1-1
ENV ANSIBLE_VERSION=2.10.7+merged+base+2.10.8+dfsg-1
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    ansible=${ANSIBLE_VERSION} \
    rsync \
    terraform=${TERRAFORM_VERSION} \
  && rm -rf /var/lib/apt/lists/*


SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
