ARG BASE_IMAGE=ubuntu:22.10
FROM $BASE_IMAGE

# Installs R and relevant R packages on a base Ubuntu image.

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Install R and packages required for it and its packages' installation
ENV R_BASE_VERSION 4.2.1
RUN apt-get update \
	&& apt-get install -y \
		software-properties-common \
		wget \
	\
	&& wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc \
	\
	&& export R_PACKAGE_VERSION=$(apt-cache policy r-base | grep -o "$R_BASE_VERSION[^ ]*" -m 1) \
	&& DEBIAN_FRONTEND="noninteractive" \
	apt-get install -y --allow-downgrades \
		cmake \
		libcurl4-openssl-dev \
		libfontconfig1-dev \
		libfreetype6-dev \
		libfribidi-dev \
		libharfbuzz-dev \
		libjpeg-dev \
		libmariadb-dev \
		libpng-dev \
		libsodium-dev \
		libssl-dev \
		libtiff5-dev \
		libxml2-dev \
		mysql-client \
		make \
		netcat-traditional \
		r-base-core=$R_PACKAGE_VERSION \
		r-base=$R_PACKAGE_VERSION \
		r-base-dev=$R_PACKAGE_VERSION \
		r-recommended=$R_PACKAGE_VERSION \
		ssh-client \
	&& apt-get clean
	# libfreetype6-dev      # package textshaping (for tidyverse)
	# libfribidi-dev        # package ragg (for tidyverse)
	# libharfbuzz-dev       # package ragg (for tidyverse)
	# libjpeg-dev           # package textshaping (for tidyverse)
	# libmariadb-dev        # package RMariaDB
	# libpng-dev            # package textshaping (for tidyverse)
	# libtiff5-dev          # package textshaping (for tidyverse)

# Install all R packages
COPY package-*.r /usr/src/
RUN cd /usr/src \
	&& chmod +x package-install.r \
	&& ./package-install.r 2>&1 \
	| grep -B 30 -A 20 -E "Status:|also installing|Error|ERROR|DONE"

ENV TZ=UTC

COPY docker-r-dojo/tests/test.r docker-r-dojo/tests/test.r

USER root
