ARG BASE_IMAGE_TAG=latest
ARG BASE_IMAGE=trovediary/trove-r-base:$BASE_IMAGE_TAG
FROM $BASE_IMAGE

# Adds Dojo to the base R image, plus some default config.

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /sbin/tini
RUN chmod +x /sbin/tini

# Install common Dojo scripts
ENV DOJO_VERSION=0.10.3
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo git ca-certificates && \
  git clone --depth 1 -b ${DOJO_VERSION} https://github.com/kudulab/dojo.git /tmp/dojo_git &&\
  /tmp/dojo_git/image_scripts/src/install.sh && \
  rm -r /tmp/dojo_git && \
  echo 'dojo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

WORKDIR /dojo/work

ENTRYPOINT ["/tini", "-g", "--", "/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]

ENV DIARY_DB_HOSTNAME=db \
	DIARY_DB_DATABASE=diary \
	DIARY_DB_USERNAME=diary \
	DIARY_DB_PASSWORD=secret \
	DIARY_DB_SOURCE=fac_diary \
	DIARY_DB_RAW_TABLE=entry_raw \
	DIARY_DB_LEGACY_TABLE=entry_legacy \
	DIARY_R_API_PORT=3041

EXPOSE 3041
