ARG BASE_IMAGE=ubuntu:22.04
FROM --platform=linux/x86_64 $BASE_IMAGE

# Installs R and relevant R packages on a base Ubuntu image.

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ENV TINI_VERSION=v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Install R and packages required for it and its packages' installation
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		software-properties-common \
		wget \
    && apt-get clean

ENV R_BASE_VERSION=4.5.
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc \
    && add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" \
	\
	&& export R_PACKAGE_VERSION=$(apt-cache policy r-base | grep -o "${R_BASE_VERSION//./\.}[^ ]*" -m 1) \
    && ([ -n "$R_PACKAGE_VERSION" ] || (echo "No R package version found matching ${R_BASE_VERSION}. Available:" >&2 && apt-cache policy r-base >&2 && false)) \
	&& DEBIAN_FRONTEND="noninteractive" \
	apt-get install -y --allow-downgrades \
		cmake \
		# package systemfonts
		fontconfig \
		# packages ragg, systemfonts
		libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libwebp-dev \
		libcurl4-openssl-dev \
		libfontconfig1-dev \
		# package textshaping (for tidyverse)
		libfreetype6-dev \
		# package ragg (for tidyverse)
		libfribidi-dev \
		# package ragg (for tidyverse)
		libharfbuzz-dev \
		# package textshaping (for tidyverse)
		libjpeg-dev \
		# package RMariaDB
		libmariadb-dev \
		# package textshaping (for tidyverse)
		libpng-dev \
		libsodium-dev \
		# package httr
		libssl-dev \
		# package textshaping (for tidyverse)
		libtiff5-dev \
		libxml2-dev \
		mysql-client \
		make \
		netcat-traditional \
		r-base-core=$R_PACKAGE_VERSION \
		r-base=$R_PACKAGE_VERSION \
		r-base-dev=$R_PACKAGE_VERSION \
		r-recommended=$R_PACKAGE_VERSION \
		ssh-client \
	&& apt-get clean

# Install all R packages
COPY package-*.r /usr/src/
RUN cd /usr/src \
	&& chmod +x package-install.r \
	&& ./package-install.r 2>&1 \
    # Ignore errors here; the next step will then only "install" any problematic/broken packages.
    || true

# Separate layer to reproduce just the errors that occurred in the previous step but were ignored.
RUN cd /usr/src && ./package-install.r 2>&1

ENV TZ=UTC

USER root
