ARG BASE_IMAGE
FROM $BASE_IMAGE

# Tools found only on the composite, without their own bespoke images

# Terraform repository
RUN (curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -) && \
  apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

RUN add-apt-repository ppa:ansible/ansible-2.10

RUN cd /tmp/ \
  && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip" \
  && unzip -q awscliv2.zip \
  && ./aws/install \
  && rm -rf ./aws

# repository packages
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    ansible=2.10.7-1ppa~focal \
    rsync \
    terraform=1.0.4 \
  && rm -rf /var/lib/apt/lists/*


SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
