ARG BASE_IMAGE_TAG=latest
FROM --platform=linux/x86_64 trovediary/trove-node-base:$BASE_IMAGE_TAG

# Note: this image is not currently used in the composite image.
# It merely installs dojo on a base.

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /sbin/tini
RUN chmod +x /sbin/tini

# Install common Dojo scripts
ENV DOJO_VERSION=0.13.0
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sudo git ca-certificates && \
  git clone --depth 1 -b ${DOJO_VERSION} https://github.com/kudulab/dojo.git /tmp/dojo_git &&\
  /tmp/dojo_git/image_scripts/src/install.sh && \
  rm -r /tmp/dojo_git && \
  echo 'dojo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

# Trust whatever's mounted into the image
RUN git config --global --add safe.directory '*'
WORKDIR /dojo/work

ENTRYPOINT ["/sbin/tini", "-g", "--", "/usr/bin/entrypoint.sh"]

CMD ["/bin/bash"]
