ARG FROM_IMAGE_TAG=latest
# NB FROM_IMAGE_TAG should be overridden by command line
FROM trovediary/trove-r-base:$FROM_IMAGE_TAG

# Install common Dojo scripts
RUN userdel docker
ENV DOJO_VERSION=0.10.3
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  sudo git ca-certificates && \
  git clone --depth 1 -b ${DOJO_VERSION} https://github.com/kudulab/dojo.git /tmp/dojo_git &&\
  /tmp/dojo_git/image_scripts/src/install.sh && \
  rm -r /tmp/dojo_git

COPY docker-r-dojo/profile /home/dojo/.profile
COPY docker-r-dojo/bashrc /home/dojo/.bashrc
RUN chown dojo:dojo /home/dojo/.profile /home/dojo/.bashrc

ENTRYPOINT ["/tini", "-g", "--", "/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]

ENV DIARY_DB_HOSTNAME=db \
	DIARY_DB_DATABASE=diary \
	DIARY_DB_USERNAME=diary \
	DIARY_DB_PASSWORD=secret \
	DIARY_DB_SOURCE=fac_diary \
	DIARY_DB_RAW_TABLE=entry_raw \
	DIARY_DB_LEGACY_TABLE=entry_legacy \
	DIARY_R_API_PORT=3041

EXPOSE 3041
