ARG BASE_IMAGE
FROM $BASE_IMAGE

# Tools found only on the composite, without their own bespoke images

# Terraform repository
RUN (curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -) && \
  apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

RUN cd /tmp/ \
  && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip" \
  && unzip -q awscliv2.zip \
  && ./aws/install \
  && rm -rf ./aws

# repository packages
ENV TERRAFORM_VERSION=1.2.3
ENV ANSIBLE_VERSION=5.5.0-1
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    ansible=${ANSIBLE_VERSION} \
    rsync \
    terraform=${TERRAFORM_VERSION} \
  && rm -rf /var/lib/apt/lists/*


SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
