ARG BASE_IMAGE=ubuntu:20.04
FROM $BASE_IMAGE

# This file installs node.js, and a load of packages, on a base Ubuntu image.

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ENV NODE_VERSION 14.15.3
RUN apt-get update \
	&& apt-get install --no-install-recommends -y \
		ca-certificates \
		curl \
		less \
		make \
		mysql-client \
		netcat \
		wget \
	&& apt-get clean \
	&& curl -L -o node.tar.gz "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" \
	&& tar -xf node.tar.gz -C /usr/local --strip-components=1 \
	&& rm node.tar.gz \
	&& ln -s /usr/local/bin/node /usr/local/bin/nodejs

# Install yarn
ENV YARN_VERSION 1.22.10
RUN curl -L -o yarn.tar.gz "https://yarnpkg.com/downloads/${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz" && \
	tar -xzf yarn.tar.gz -C /opt/ && \
	rm yarn.tar.gz && \
	ln -s /opt/yarn-v${YARN_VERSION}/bin/yarn /usr/local/bin/yarn && \
	ln -s /opt/yarn-v${YARN_VERSION}/bin/yarnpkg /usr/local/bin/yarnpkg

RUN yarn global add newman@^5.2.4 db-migrate@^0.11.12 db-migrate-mysql@^2.1.2
