format_version: 5
pipelines:
  trove-docker:
    group: trove
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    secure_variables:
      DOCKERHUB_ACCESS_TOKEN: "AES:RqxzOJtudcfMZhtRW9o6+Q==:7mPcoVXAbowOY6T5e04SIqRQRZGydXIftxD5J6rjVNJyPmEH14g/to/LyNaWd8au"
    stages:
      - build-base:
          clean_workspace: true
          jobs:
            r-base:
              tasks:
               - exec:
                   command: make
                   arguments:
                   - push-docker-r-base
            r-lambda:
              tasks:
               - exec:
                   command: make
                   arguments:
                   - push-docker-r-lambda
            node:
              tasks:
               - exec:
                   command: make
                   arguments:
                   - push-docker-node-base
            composite:
              tasks:
              - exec:
                  command: make
                  arguments:
                  - push-docker-composite-circleci
              - exec:
                  command: make
                  arguments:
                  - push-docker-composite-dojo
      - build-dojo:
          clean_workspace: true
          jobs:
            r:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-r-dojo"
            node:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-node-dojo"
            tex:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "push-docker-tex-dojo"
      - test:
          clean_workspace: true
          jobs:
            node-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-node-dojo"
            r-base:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-r-base"
            r-lambda:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-r-lambda"
            r-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-r-dojo"
            composite:
              tasks:
              - exec:
                  command: make
                  arguments:
                  - test-docker-composite-node
              - exec:
                  command: make
                  arguments:
                  - test-docker-composite-r
              - exec:
                  command: make
                  arguments:
                  - test-docker-composite-terraform
            tex-dojo:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "test-docker-tex-dojo"
      - save:
          clean_workspace: true
          environment_variables:
            GIT_AUTHOR_NAME: GoCD pipeline
            GIT_AUTHOR_EMAIL: trove@gocd.martinmccaffery.com
            GIT_COMMITTER_NAME: GoCD pipeline
            GIT_COMMITTER_EMAIL: trove@gocd.martinmccaffery.com
          jobs:
            update-trove:
              tasks:
               - exec:
                   command: make
                   arguments:
                    - "gocd-dependencies-push-update"

  trove-docker-update:
    group: trove
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        auto_update: false
    environment_variables:
      GIT_AUTHOR_NAME: GoCD pipeline
      GIT_AUTHOR_EMAIL: trove-docker@gocd.martinmccaffery.com
      GIT_COMMITTER_NAME: GoCD pipeline
      GIT_COMMITTER_EMAIL: trove-docker@gocd.martinmccaffery.com
    stages:
      - get-updates:
          clean_workspace: true
          approval: manual
          tasks:
           - exec:
               command: make
               arguments:
                - gocd-dependencies-get-updates
